# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        gan: 3
        recommend: 3
        embedding: 3
        search: 3
        vision: 3
        graph: 3
        image: 3


# 通知の閾値
score_threshold: 0
