# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        gan: 5
        recommend: 5
        embedding: 5
        search: 5
        vision: 5
        graph: 5
        image: 5


# 通知の閾値
score_threshold: 10
